import { MapPin, Moon, Briefcase, Shirt, ShieldCheck, Ruler, Gift, Truck, Package, RotateCcw, Lock } from "lucide-react";

export const FABRIC_NOTE = "220gsm combed cotton, DTF print with sharp detail";

export const PRODUCTS = [
  {
    id: 1,
    name: "Silent Faces",
    theme: "Soft & Thoughtful",
    price: 799,
    originalPrice: 890,
    tagline: "For the ones who feel deeply without saying a word.",
    description: "Abstract portrait composition by Sara Emad. Every line tells an introspective story. Drawn digitally from scratch to capture the weight and beauty of an inner world.",
    descriptionAr: "تصميم بورتريه تجريدي يجمع المشاعر بدون كلمات. كل خط يحمل قصة، مرسوم بشغف ليبرز العمق النفسي.",
    artistName: "Sara Emad",
    fit: "Oversized",
    fitNote: "Runs 1 size larger than standard. If you're between sizes, go with your usual.",
    badge: "Bestseller",
    badgeReason: "Top seller across 3 consecutive drops",
    stock: 18,
    sizes: ["S", "M", "L", "XL"],
    fabric: FABRIC_NOTE,
    image: "/images/theme/prod_1.png",
  },
  {
    id: 2,
    name: "Nile Energy",
    theme: "Proud & Rooted",
    price: 799,
    tagline: "Wear where you're from.",
    description: "A digital tribute to the pulse of Cairo. Sharp contrast lines and bold framing make this piece unmistakable from a distance.",
    descriptionAr: "تصميم يعبر عن طاقة القاهرة وروح النيل بخطوط حادة وواضحة، لتفخر بجذورك في كل تفصيلة.",
    artistName: "Amira Khalil",
    fit: "Regular",
    fitNote: "True to size. Choose your standard tee size.",
    badge: "New",
    badgeReason: "Dropped this week",
    stock: 24,
    sizes: ["M", "L", "XL", "XXL"],
    fabric: FABRIC_NOTE,
    image: "/images/theme/prod_2.png",
  },
  {
    id: 3,
    name: "Scorpio Silence",
    theme: "Cosmic",
    price: 899,
    tagline: "Your sign. Your style.",
    description: "An illustration dedicated to the intense, unspoken depth of water signs. Features subtle celestial motifs and intricate shadow work.",
    descriptionAr: "تصميم يعكس الغموض والعمق للأبراج المائية بتفاصيل فلكية مرسومة بدقة لتناسب شخصيتك.",
    artistName: "Youssef Nabil",
    fit: "Oversized",
    fitNote: "Boxy, relaxed drape. Stick to true size for the intended fit.",
    badge: null,
    badgeReason: null,
    stock: 12,
    sizes: ["S", "M", "L", "XL"],
    fabric: FABRIC_NOTE,
    image: "/images/theme/prod_3.png",
  },
  {
    id: 4,
    name: "The Builder",
    theme: "Weird & Wonderful",
    price: 799,
    tagline: "For the ones who don't fit one box.",
    description: "An homage to the creative process. Raw, surrealistic architectural forms blending into human elements. Perfect for the studio or the street.",
    descriptionAr: "تكريم لعملية الإبداع بأشكال سريالية تمزج بين الخيال والهندسة لتلهمك كل يوم.",
    artistName: "Dina El Mofty",
    fit: "Regular",
    fitNote: "Form-fitting across the shoulders, relaxed bottom.",
    badge: "New",
    badgeReason: "Dropped this week",
    stock: 30,
    sizes: ["S", "M", "L", "XL", "XXL"],
    fabric: FABRIC_NOTE,
    image: "/images/theme/prod_4.png",
  },
  {
    id: 5,
    name: "Quiet Storm",
    theme: "Soft & Thoughtful",
    price: 799,
    tagline: "Still waters run deep.",
    description: "Minimalist linework capturing the beauty of calm resilience. This design speaks volumes to those who understand it, while remaining understated.",
    descriptionAr: "خطوط بسيطة تعبر عن القوة الهادئة. تصميم يحكي الكثير لمن يفهمه بدون أي مبالغة.",
    artistName: "Sara Emad",
    fit: "Oversized",
    fitNote: "Runs large. Size down if you prefer a standard fit.",
    badge: "Almost Gone",
    badgeReason: "Only 6 left from this illustration run",
    stock: 6,
    sizes: ["M", "L", "XL"],
    fabric: FABRIC_NOTE,
    image: "/images/theme/prod_1.png",
  },
  {
    id: 6,
    name: "Leo Fire",
    theme: "Cosmic",
    price: 899,
    tagline: "Bold, warm, and impossible to ignore.",
    description: "A tribute to fire signs—radiant, expressive, and confident. The illustration uses warm gradients and sharp framing to command attention.",
    descriptionAr: "تصميم يعبر عن الأبراج النارية.. جريء ودافئ ومستحيل يتجاهله حد. تفاصيل تلفت النظر.",
    artistName: "Amira Khalil",
    fit: "Regular",
    fitNote: "True to size.",
    badge: null,
    badgeReason: null,
    stock: 15,
    sizes: ["S", "M", "L", "XL"],
    fabric: FABRIC_NOTE,
    image: "/images/theme/prod_2.png",
  },
  {
    id: 7,
    name: "First Chapter",
    theme: "Gift Something Real",
    price: 999,
    originalPrice: 1199,
    tagline: "Mark the milestone with art that lasts.",
    description: "A graduation-worthy graphic symbolizing new beginnings. Full gift bundle includes rigid box, story card, and tissue wrap.",
    descriptionAr: "تصميم يوثق البدايات الجديدة والتخرج. باقة هدية متكاملة مغلفة بشكل راقي لتقديمها مباشرة.",
    artistName: "Nour Abdel Salam",
    fit: "Oversized",
    fitNote: "Generous drape, heavy fabric feel.",
    badge: "Bundle",
    badgeReason: "Gift-ready packaging included",
    stock: 22,
    sizes: ["S", "M", "L", "XL", "XXL"],
    fabric: FABRIC_NOTE,
    image: "/images/theme/prod_3.png",
  },
  {
    id: 8,
    name: "Ibn El Balad",
    theme: "Bold & Loud",
    price: 799,
    tagline: "For when you want to be noticed.",
    description: "Unapologetic street identity. This illustration pulls directly from the energy of Cairo's core neighborhoods, meant exactly as it reads.",
    descriptionAr: "هوية شارع حقيقية ومباشرة. تصميم مستوحى من طاقة وسط البلد لكل حد فخور بأصله.",
    artistName: "Youssef Nabil",
    fit: "Regular",
    fitNote: "Standard fit, slightly tapered sleeves.",
    badge: "Bestseller",
    badgeReason: "Top seller across 3 consecutive drops",
    stock: 9,
    sizes: ["M", "L", "XL"],
    fabric: FABRIC_NOTE,
    image: "/images/theme/prod_4.png",
  },
];

export const VIBES_CARDS = [
  {
    title: "Bold & Loud",
    desc: "For when you want to be noticed.",
    image: "/images/theme/prod_4.png",
    span: "col-span-1 md:col-span-2 row-span-2",
  },
  {
    title: "Soft & Thoughtful",
    desc: "For the quiet ones who feel deeply.",
    image: "/images/theme/prod_1.png",
    span: "col-span-1 md:col-span-1 row-span-1",
  },
  {
    title: "Proud & Rooted",
    desc: "Wear where you're from.",
    image: "/images/theme/hero_bg.png",
    span: "col-span-1 md:col-span-1 row-span-1",
  },
  {
    title: "Weird & Wonderful",
    desc: "For the ones who don't fit one box.",
    image: "/images/theme/prod_3.png",
    span: "col-span-1 md:col-span-1 row-span-1",
  },
  {
    title: "Cosmic",
    desc: "Your sign. Your style.",
    image: "/images/theme/prod_2.png",
    span: "col-span-1 md:col-span-1 row-span-1",
  },
];

export const UGC = [
  {
    name: "Yahia, Alexandria",
    product: "Nile Energy",
    quote: "Actually looks like art, not just another graphic tee.",
    img: "/images/theme/prod_2.png",
  },
  {
    name: "Mariam, Cairo",
    product: "The Overthinker",
    quote: "Found a design that says what I couldn't say directly.",
    img: "/images/theme/prod_1.png",
  },
  {
    name: "Omar, Mansoura",
    product: "The Builder",
    quote: "Material is heavier than most brands here. Wash tested it thrice, still sharp.",
    img: "/images/theme/prod_4.png",
  },
];

export const ASSURANCE = [
  {
    icon: Shirt,
    title: "Original illustration",
    text: "Every design starts from a fresh digital concept, not a copied trend board.",
  },
  {
    icon: ShieldCheck,
    title: "Premium-feel finish",
    text: "220gsm combed cotton with DTF printing. Heavier and sharper than a typical print-shop tee.",
  },
  {
    icon: Ruler,
    title: "Fit guidance before checkout",
    text: "Size chart, fit notes, and body-type recommendations visible on every product page.",
  },
  {
    icon: Gift,
    title: "Gift-ready presentation",
    text: "Built for self-expression and for gifts that feel chosen, not random.",
  },
];

export const TRUST = [
  { icon: Truck, label: "Free shipping on prepaid" },
  { icon: Package, label: "COD available nationwide" },
  { icon: RotateCcw, label: "14-day exchange policy" },
  { icon: Lock, label: "Secure checkout (SSL)" },
];
